#
# Cache
#
varnish:
  ports:
  - 7988:80/tcp
  restart: always
  environment:
    BACKENDS: loadbalancer:80
  tty: true
  image: eeacms/varnish
  links:
  - loadbalancer:loadbalancer
  volumes:
  - /etc/varnish
  stdin_open: true
  labels:
    io.rancher.scheduler.affinity:host_label: www-frontend=yes

memcached:
  restart: always
  environment:
    MEMCACHED_MEMORY: '2048'
  labels:
    io.rancher.scheduler.affinity:host_label: www-frontend=yes
  image: eeacms/memcached:1.4
  volumes:
  - /etc/localtime:/etc/localtime:ro

relcached:
  restart: always
  environment:
    MEMCACHED_MEMORY: '2048'
  labels:
    io.rancher.scheduler.affinity:host_label: www-frontend=yes
  image: eeacms/memcached:1.4
  volumes:
  - /etc/localtime:/etc/localtime:ro

#
# Mail
#
postfix:
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: www-frontend=yes
  environment:
    MTP_HOST: eea.europa.eu
  image: eeacms/postfix
  volumes:
  - /etc/localtime:/etc/localtime:ro

#
# LB
#
loadbalancer:
  restart: always
  expose:
  - 80:80
  labels:
    io.rancher.scheduler.affinity:host_label: www-lb=yes
  tty: true
  image: rancher/load-balancer-service
  links:
  - plone:plone
  stdin_open: true

#
# Web App
#
plone:
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: www-plone=yes
    io.rancher.scheduler.affinity:host_label: docker-volume-netshare=yes
    io.rancher.sidekicks: plone_data
  image: eeacms/plone-eea-www
  links:
  - memcached:memcached
  - relcached:relcached
  - postfix:postfix
  - postgres:postgres
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - plone_data

plone_data:
  restart: always
  command: sh -c "chown -v -R 500:500 /data >> /data/chown.log && exec tail -f /data/chown.log"
  tty: true
  image: busybox
  volumes:
  - 10.142.71.23/mnt/vdb1/sharedblobstorage/blobs:/data/blobs
  - 10.142.71.23/mnt/vdb1/sharedblobstorage/downloads:/data/downloads
  - 10.142.71.23/mnt/vdb1/sharedblobstorage/www-static-resources:/data/www-static-resources
  - 10.142.71.23/mnt/vdb1/sharedblobstorage/eea.controlpanel:/data/eea.controlpanel
  volume_driver: nfs
  stdin_open: true

ploneasync:
  restart: always
  environment:
    BUILDOUT_REBUILD: 'true'
    PLONE_APP_ASYNC: single_db_worker
  image: eeacms/plone-eea-www
  labels:
    io.rancher.sidekicks: ploneasync_data
    io.rancher.scheduler.affinity:host_label: www-plone=yes
    io.rancher.scheduler.affinity:host_label: docker-volume-netshare=yes
  links:
  - memcached:memcached
  - relcached:relcached
  - postfix:postfix
  - postgres:postgres
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - ploneasync_data

ploneasync_data:
  restart: always
  command: sh -c "chown -v -R 500:500 /data >> /data/chown.log && exec tail -f /data/chown.log"
  tty: true
  image: busybox
  volumes:
  - 10.142.71.23/mnt/vdb1/sharedblobstorage/blobs:/data/blobs
  - 10.142.71.23/mnt/vdb1/sharedblobstorage/downloads:/data/downloads
  - 10.142.71.23/mnt/vdb1/sharedblobstorage/www-static-resources:/data/www-static-resources
  - 10.142.71.23/mnt/vdb1/sharedblobstorage/eea.controlpanel:/data/eea.controlpanel
  volume_driver: nfs
  stdin_open: true

#
# DB
#
postgres:
  image: rancher/dns-service
  links:
  - postgres1:postgres1

postgres1:
  restart: always
  environment:
    POSTGRES_DBNAME: datafs zasync
    POSTGRES_DBPASS: zope
    POSTGRES_DBUSER: zope
  labels:
    io.rancher.sidekicks: postgres_data
    io.rancher.scheduler.affinity:host_label: www-db=yes
  tty: true
  image: eeacms/postgres:9.4
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - postgres_data
  stdin_open: true

postgres_data:
  restart: always
  command: sh -c "chown -v -R 999:999 /var/lib/postgresql/data >> /data/chown.log && exec tail -f /data/chown.log"
  tty: true
  image: busybox
  volumes:
  - /var/lib/postgresql/data
  - /data
  stdin_open: true
