memcached:
  restart: always
  tty: true
  image: eeacms/memcached
  stdin_open: true
varnish:
  ports:
  - 8888:80/tcp
  restart: always
  environment:
    BACKENDS: loadbalancer:80
  labels:
    io.rancher.scheduler.affinity:host_label: type=frontend
  tty: true
  image: eeacms/varnish
  links:
  - loadbalancer:loadbalancer
  volumes:
  - /etc/varnish
  stdin_open: true
loadbalancer:
  restart: always
  expose:
  - 80:80
  labels:
    io.rancher.scheduler.affinity:host_label: type=frontend
  tty: true
  image: rancher/load-balancer-service
  links:
  - Plone:Plone
  stdin_open: true
postgres:
  restart: always
  environment:
    POSTGRES_DBNAME: datafs zasync
    POSTGRES_DBUSER: zope
    POSTGRES_DBPASS: zope
  labels:
    io.rancher.scheduler.affinity:host_label: type=db
  tty: true
  image: eeacms/postgres:9.4
  volumes:
  - /var/lib/postgresql/data
  stdin_open: true
Plone:
  restart: always
  labels:
    io.rancher.scheduler.affinity:host_label: type=backend
  tty: true
  image: eeacms/plone-eea-www
  links:
  - memcached:memcached
  - postgres:postgres
  stdin_open: true
